import 'dart:math';

import 'package:prosemirror/src/dependencies/rope_sequence/rope_sequence.dart';
import 'package:prosemirror/src/state/plugin.dart';
import 'package:prosemirror/src/state/selection.dart';
import 'package:prosemirror/src/state/state.dart';
import 'package:prosemirror/src/state/transaction.dart';
import 'package:prosemirror/src/transform/map.dart';
import 'package:prosemirror/src/transform/step.dart';
import 'package:prosemirror/src/transform/transform.dart';

// ProseMirror's history isn't simply a way to roll back to a previous
// state, because ProseMirror supports applying changes without adding
// them to the history (for example during collaboration).
//
// To this end, each 'Branch' (one for the undo history and one for
// the redo history) keeps an array of 'Items', which can optionally
// hold a step (an actual undoable change), and always hold a position
// map (which is needed to move changes below them to apply to the
// current document).
//
// An item that has both a step and a selection bookmark is the start
// of an 'event' - a group of changes that will be undone or redone at
// once. (It stores only the bookmark, since that way we don't have to
// provide a document until the selection is actually applied, which
// is useful when compressing.)

/// The options accepted by the [history] plugin.
class HistoryOptions {
  /// Create a set of history options.
  HistoryOptions({this.depth, this.newGroupDelay});

  /// The amount of history events that are collected before the oldest
  /// events are discarded. Defaults to 100.
  final int? depth;

  /// The delay between changes after which a new group should be started.
  /// Defaults to 500 (milliseconds). Note that when changes aren't
  /// adjacent, a new group is always started.
  final int? newGroupDelay;
}

final PluginKey _historyKey = PluginKey("history");
final PluginKey _closeHistoryKey = PluginKey("closeHistory");

/// Returns a plugin that enables the undo history for an editor. The
/// plugin will track undo and redo stacks, which can be used with the
/// [undo] and [redo] commands.
///
/// You can set an `"addToHistory"` metadata property of `false` on a
/// transaction to prevent it from being rolled back by undo.
Plugin history([HistoryOptions? config]) {
  final resolvedConfig = HistoryOptions(depth: config?.depth ?? 100, newGroupDelay: config?.newGroupDelay ?? 500);

  return Plugin(
    PluginSpec(
      key: _historyKey,
      state: StateField(
        init: (stateConfig, instance) {
          return HistoryState(Branch.empty, Branch.empty, null, 0, -1);
        },
        apply: (tr, history, oldState, newState) {
          return _applyTransaction(history as HistoryState, oldState, tr, resolvedConfig);
        },
      ),
      extra: {"config": resolvedConfig},
    ),
  );
}

/// Set a flag on the given transaction that will prevent further steps
/// from being appended to an existing history event (so that they
/// require a separate undo command to undo).
Transaction closeHistory(Transaction tr) {
  return tr.setMeta(_closeHistoryKey, true);
}

/// A command function that undoes the last change, if any.
final Command undo = _buildCommand(false, true);

/// A command function that redoes the last undone change, if any.
final Command redo = _buildCommand(true, true);

/// A command function that undoes the last change. Don't scroll the
/// selection into view.
final Command undoNoScroll = _buildCommand(false, false);

/// A command function that redoes the last undone change. Don't scroll
/// the selection into view.
final Command redoNoScroll = _buildCommand(true, false);

/// Builds an undo or redo command.
FunctionCommand _buildCommand(bool redo, bool scroll) {
  return FunctionCommand((state, [dispatch, view]) {
    final history = _historyKey.getState(state) as HistoryState?;
    if (history == null || (redo ? history.undone : history.done).eventCount == 0) {
      return false;
    }
    if (dispatch != null) {
      final tr = _histTransaction(history, state, redo);
      if (tr != null) {
        dispatch(scroll ? tr.scrollIntoView() : tr);
      }
    }
    return true;
  });
}

/// The amount of undoable events available in a given state.
int undoDepth(EditorState state) {
  final history = _historyKey.getState(state) as HistoryState?;
  return history != null ? history.done.eventCount : 0;
}

/// The amount of redoable events available in a given editor state.
int redoDepth(EditorState state) {
  final history = _historyKey.getState(state) as HistoryState?;
  return history != null ? history.undone.eventCount : 0;
}

/// Returns true if the given transaction was generated by the history
/// plugin.
bool isHistoryTransaction(Transaction tr) {
  return tr.getMeta(_historyKey) != null;
}

/// The meta value the history plugin stores on the transactions it
/// generates. It is read back in [_applyTransaction].
typedef _HistoryMeta = ({bool redo, HistoryState historyState});

// Apply the latest event from one branch to the document and shift the
// event onto the other branch.
Transaction? _histTransaction(HistoryState history, EditorState state, bool redo) {
  final preserveItems = _mustPreserveItems(state);
  final histOptions = _historyKey.get(state)!.spec.extra["config"] as HistoryOptions;
  final pop = (redo ? history.undone : history.done)._popEvent(state, preserveItems);
  if (pop == null) {
    return null;
  }

  final selection = pop.selection!.resolve(pop.transform.doc);
  final added = (redo ? history.done : history.undone).addTransform(
    pop.transform,
    state.selection.getBookmark(),
    histOptions,
    preserveItems,
  );

  final newHistory = HistoryState(redo ? added : pop.remaining, redo ? pop.remaining : added, null, 0, -1);
  return pop.transform.setSelection(selection).setMeta(_historyKey, (redo: redo, historyState: newHistory));
}

bool _cachedPreserveItems = false;
List<Plugin>? _cachedPreserveItemsPlugins;

// Check whether any plugin in the given state has a
// `historyPreserveItems` property in its spec, in which case we must
// preserve steps exactly as they came in, so that they can be rebased.
bool _mustPreserveItems(EditorState state) {
  final plugins = state.plugins;
  if (!identical(_cachedPreserveItemsPlugins, plugins)) {
    _cachedPreserveItems = false;
    _cachedPreserveItemsPlugins = plugins;
    for (var index = 0; index < plugins.length; index++) {
      if (plugins[index].spec.extra["historyPreserveItems"] == true) {
        _cachedPreserveItems = true;
        break;
      }
    }
  }
  return _cachedPreserveItems;
}

const int _depthOverflow = 20;

// Record a transformation in undo history.
HistoryState _applyTransaction(HistoryState history, EditorState state, Transaction tr, HistoryOptions options) {
  final historyTr = tr.getMeta(_historyKey) as _HistoryMeta?;
  if (historyTr != null) {
    return historyTr.historyState;
  }

  var currentHistory = history;
  if (tr.getMeta(_closeHistoryKey) != null) {
    currentHistory = HistoryState(currentHistory.done, currentHistory.undone, null, 0, -1);
  }

  final appended = tr.getMeta("appendedTransaction") as Transaction?;

  if (tr.steps.isEmpty) {
    return currentHistory;
  } else if (appended != null && appended.getMeta(_historyKey) != null) {
    final appendedMeta = appended.getMeta(_historyKey) as _HistoryMeta;
    if (appendedMeta.redo) {
      return HistoryState(
        currentHistory.done.addTransform(tr, null, options, _mustPreserveItems(state)),
        currentHistory.undone,
        _rangesFor(tr.mapping.maps),
        currentHistory.prevTime,
        currentHistory.prevComposition,
      );
    } else {
      return HistoryState(
        currentHistory.done,
        currentHistory.undone.addTransform(tr, null, options, _mustPreserveItems(state)),
        null,
        currentHistory.prevTime,
        currentHistory.prevComposition,
      );
    }
  } else if (tr.getMeta("addToHistory") != false && !(appended != null && appended.getMeta("addToHistory") == false)) {
    // Group transforms that occur in quick succession into one event.
    final composition = tr.getMeta("composition") as int?;
    final newGroup =
        currentHistory.prevTime == 0 ||
        (appended == null &&
            currentHistory.prevComposition != composition &&
            (currentHistory.prevTime < tr.time - options.newGroupDelay! ||
                !_isAdjacentTo(tr, currentHistory.prevRanges)));
    final prevRanges = appended != null
        ? _mapRanges(currentHistory.prevRanges, tr.mapping)
        : _rangesFor(tr.mapping.maps);
    return HistoryState(
      currentHistory.done.addTransform(
        tr,
        newGroup ? state.selection.getBookmark() : null,
        options,
        _mustPreserveItems(state),
      ),
      Branch.empty,
      prevRanges,
      tr.time,
      composition ?? currentHistory.prevComposition,
    );
  } else {
    final rebased = tr.getMeta("rebased") as int?;
    if (rebased != null) {
      // Used by the collab module to tell the history that some of its
      // content has been rebased.
      return HistoryState(
        currentHistory.done.rebased(tr, rebased),
        currentHistory.undone.rebased(tr, rebased),
        _mapRanges(currentHistory.prevRanges, tr.mapping),
        currentHistory.prevTime,
        currentHistory.prevComposition,
      );
    } else {
      return HistoryState(
        currentHistory.done.addMaps(tr.mapping.maps),
        currentHistory.undone.addMaps(tr.mapping.maps),
        _mapRanges(currentHistory.prevRanges, tr.mapping),
        currentHistory.prevTime,
        currentHistory.prevComposition,
      );
    }
  }
}

bool _isAdjacentTo(Transform transform, List<int>? prevRanges) {
  if (prevRanges == null) {
    return false;
  }
  if (!transform.docChanged) {
    return true;
  }
  var adjacent = false;
  transform.mapping.maps[0].forEach((start, end, newStart, newEnd) {
    for (var index = 0; index < prevRanges.length; index += 2) {
      if (start <= prevRanges[index + 1] && end >= prevRanges[index]) {
        adjacent = true;
      }
    }
  });
  return adjacent;
}

List<int> _rangesFor(List<StepMap> maps) {
  final result = <int>[];
  for (var index = maps.length - 1; index >= 0 && result.isEmpty; index--) {
    maps[index].forEach((oldFrom, oldTo, from, to) {
      result.add(from);
      result.add(to);
    });
  }
  return result;
}

List<int>? _mapRanges(List<int>? ranges, Mapping mapping) {
  if (ranges == null) {
    return null;
  }
  final result = <int>[];
  for (var index = 0; index < ranges.length; index += 2) {
    final from = mapping.map(ranges[index], 1);
    final to = mapping.map(ranges[index + 1], -1);
    if (from <= to) {
      result.add(from);
      result.add(to);
    }
  }
  return result;
}

/// The value of the state field that tracks undo/redo history for that
/// state. Will be stored in the plugin state when the history plugin is
/// active.
class HistoryState {
  /// Create a history state.
  HistoryState(this.done, this.undone, this.prevRanges, this.prevTime, this.prevComposition);

  /// The undo branch. This is mutable so that the test suite can rewrite
  /// it in place after a compression.
  Branch done;

  /// The redo branch.
  final Branch undone;

  /// The ranges touched by the previous transaction, used for grouping.
  final List<int>? prevRanges;

  /// The timestamp of the previous transaction.
  final int prevTime;

  /// The composition id of the previous transaction.
  final int prevComposition;
}

// Used to schedule history compression.
const int _maxEmptyItems = 500;

/// The result of popping an event off a [Branch].
class _PopResult {
  _PopResult(this.remaining, this.transform, this.selection);

  final Branch remaining;
  final Transaction transform;
  final SelectionBookmark? selection;
}

/// A branch of the history (either the undo or redo stack).
class Branch {
  /// Create a branch.
  Branch(this.items, this.eventCount);

  /// The items that make up this branch.
  final RopeSequence<Item> items;

  /// The number of events (undoable groups) on this branch.
  final int eventCount;

  /// The empty branch.
  static final Branch empty = Branch(RopeSequence.from<Item>(<Item>[]), 0);

  // Pop the latest event off the branch's history and apply it to a
  // document transform.
  _PopResult? _popEvent(EditorState state, bool preserveItems) {
    if (eventCount == 0) {
      return null;
    }

    var end = items.length;
    for (; ; end--) {
      final next = items.get(end - 1);
      if (next!.selection != null) {
        --end;
        break;
      }
    }

    Mapping? remap;
    int? mapFrom;
    if (preserveItems) {
      remap = remapping(end, items.length);
      mapFrom = remap.maps.length;
    }
    final transform = state.tr;
    SelectionBookmark? selection;
    Branch? remaining;
    final addAfter = <Item>[];
    final addBefore = <Item>[];

    items.forEach(
      (item, index) {
        if (item.step == null) {
          if (remap == null) {
            remap = remapping(end, index + 1);
            mapFrom = remap!.maps.length;
          }
          mapFrom = mapFrom! - 1;
          addBefore.add(item);
          return null;
        }

        if (remap != null) {
          addBefore.add(Item(item.map));
          final step = item.step!.map(remap!.slice(mapFrom!));
          StepMap? map;
          if (step != null && transform.maybeStep(step).doc != null) {
            map = transform.mapping.maps[transform.mapping.maps.length - 1];
            addAfter.add(Item(map, null, null, addAfter.length + addBefore.length));
          }
          mapFrom = mapFrom! - 1;
          if (map != null) {
            remap!.appendMap(map, mapFrom);
          }
        } else {
          transform.maybeStep(item.step!);
        }

        if (item.selection != null) {
          selection = remap != null ? item.selection!.map(remap!.slice(mapFrom!)) : item.selection;
          remaining = Branch(_appendItems(items.slice(0, end), [...addBefore.reversed, ...addAfter]), eventCount - 1);
          return false;
        }
        return null;
      },
      items.length,
      0,
    );

    return _PopResult(remaining!, transform, selection);
  }

  // Create a new branch with the given transform added.
  Branch addTransform(
    Transform transform,
    SelectionBookmark? selection,
    HistoryOptions histOptions,
    bool preserveItems,
  ) {
    final newItems = <Item>[];
    var eventCount = this.eventCount;
    var oldItems = items;
    var lastItem = !preserveItems && oldItems.length > 0 ? oldItems.get(oldItems.length - 1) : null;
    var currentSelection = selection;

    for (var index = 0; index < transform.steps.length; index++) {
      final step = transform.steps[index].invert(transform.docs[index]);
      var item = Item(transform.mapping.maps[index], step, currentSelection);
      final merged = lastItem?.merge(item);
      if (merged != null) {
        item = merged;
        if (index != 0) {
          newItems.removeLast();
        } else {
          oldItems = oldItems.slice(0, oldItems.length - 1);
        }
      }
      newItems.add(item);
      if (currentSelection != null) {
        eventCount++;
        currentSelection = null;
      }
      if (!preserveItems) {
        lastItem = item;
      }
    }
    final overflow = eventCount - histOptions.depth!;
    if (overflow > _depthOverflow) {
      oldItems = _cutOffEvents(oldItems, overflow);
      eventCount -= overflow;
    }
    return Branch(_appendItems(oldItems, newItems), eventCount);
  }

  Mapping remapping(int from, int to) {
    final maps = Mapping();
    items.forEach(
      (item, index) {
        final mirrorOffset = item.mirrorOffset;
        final int? mirrorPos = mirrorOffset != null && index - mirrorOffset >= from
            ? maps.maps.length - mirrorOffset
            : null;
        maps.appendMap(item.map, mirrorPos);
        return null;
      },
      from,
      to,
    );
    return maps;
  }

  Branch addMaps(List<StepMap> array) {
    if (eventCount == 0) {
      return this;
    }
    return Branch(_appendItems(items, array.map((map) => Item(map)).toList()), eventCount);
  }

  // When the collab module receives remote changes, the history has to
  // know about those, so that it can adjust the steps that were rebased
  // on top of the remote changes, and include the position maps for the
  // remote changes in its array of items.
  Branch rebased(Transform rebasedTransform, int rebasedCount) {
    if (eventCount == 0) {
      return this;
    }

    final rebasedItems = <Item>[];
    final start = max(0, items.length - rebasedCount);

    final mapping = rebasedTransform.mapping;
    var newUntil = rebasedTransform.steps.length;
    var newEventCount = eventCount;
    items.forEach((item, index) {
      if (item.selection != null) {
        newEventCount--;
      }
      return null;
    }, start);

    var iRebased = rebasedCount;
    items.forEach((item, index) {
      iRebased--;
      final pos = mapping.getMirror(iRebased);
      if (pos == null) {
        return null;
      }
      newUntil = min(newUntil, pos);
      final map = mapping.maps[pos];
      if (item.step != null) {
        final step = rebasedTransform.steps[pos].invert(rebasedTransform.docs[pos]);
        final selection = item.selection?.map(mapping.slice(iRebased + 1, pos));
        if (selection != null) {
          newEventCount++;
        }
        rebasedItems.add(Item(map, step, selection));
      } else {
        rebasedItems.add(Item(map));
      }
      return null;
    }, start);

    final newMaps = <Item>[];
    for (var index = rebasedCount; index < newUntil; index++) {
      newMaps.add(Item(mapping.maps[index]));
    }
    final newBranchItems = _appendItems(_appendItems(items.slice(0, start), newMaps), rebasedItems);
    var branch = Branch(newBranchItems, newEventCount);

    if (branch.emptyItemCount() > _maxEmptyItems) {
      branch = branch.compress(items.length - rebasedItems.length);
    }
    return branch;
  }

  int emptyItemCount() {
    var count = 0;
    items.forEach((item, index) {
      if (item.step == null) {
        count++;
      }
      return null;
    });
    return count;
  }

  // Compressing a branch means rewriting it to push the air (map-only
  // items) out. During collaboration, these naturally accumulate because
  // each remote change adds one. The `upto` argument is used to ensure
  // that only the items below a given level are compressed, because
  // `rebased` relies on a clean, untouched set of items in order to
  // associate old items with rebased steps.
  Branch compress([int? upto]) {
    final resolvedUpto = upto ?? items.length;
    final remap = remapping(0, resolvedUpto);
    var mapFrom = remap.maps.length;
    final newItems = <Item>[];
    var events = 0;
    items.forEach(
      (item, index) {
        if (index >= resolvedUpto) {
          newItems.add(item);
          if (item.selection != null) {
            events++;
          }
        } else if (item.step != null) {
          final step = item.step!.map(remap.slice(mapFrom));
          final map = step?.getMap();
          mapFrom--;
          if (map != null) {
            remap.appendMap(map, mapFrom);
          }
          if (step != null) {
            final selection = item.selection?.map(remap.slice(mapFrom));
            if (selection != null) {
              events++;
            }
            final newItem = Item(map!.invert(), step, selection);
            final last = newItems.length - 1;
            final merged = newItems.isNotEmpty ? newItems[last].merge(newItem) : null;
            if (merged != null) {
              newItems[last] = merged;
            } else {
              newItems.add(newItem);
            }
          }
        } else {
          // A map-only item (no step); still consume a remap slot.
          mapFrom--;
        }
        return null;
      },
      items.length,
      0,
    );
    return Branch(RopeSequence.from(newItems.reversed.toList()), events);
  }
}

RopeSequence<Item> _cutOffEvents(RopeSequence<Item> items, int count) {
  int? cutPoint;
  var remaining = count;
  items.forEach((item, index) {
    if (item.selection != null && (remaining-- == 0)) {
      cutPoint = index;
      return false;
    }
    return null;
  });
  return items.slice(cutPoint!);
}

/// An item in a history [Branch].
class Item {
  /// Create a history item.
  Item(this.map, [this.step, this.selection, this.mirrorOffset]);

  /// The (forward) step map for this item.
  final StepMap map;

  /// The inverted step.
  final Step? step;

  /// If this is non-null, this item is the start of a group, and this
  /// selection is the starting selection for the group (the one that was
  /// active before the first step was applied).
  final SelectionBookmark? selection;

  /// If this item is the inverse of a previous mapping on the stack, this
  /// points at the inverse's offset.
  final int? mirrorOffset;

  Item? merge(Item other) {
    if (step != null && other.step != null && other.selection == null) {
      final merged = other.step!.merge(step!);
      if (merged != null) {
        return Item(merged.getMap().invert(), merged, selection);
      }
    }
    return null;
  }
}

// Appends [items] to [rope], guarding against the shared empty rope
// singleton, whose element type is `Never`. Appending a `List<Item>`
// directly onto that singleton would coerce through `Never` and silently
// drop the items, so an empty receiver is rebuilt as a typed leaf.
RopeSequence<Item> _appendItems(RopeSequence<Item> rope, List<Item> items) {
  if (rope.length == 0) {
    return RopeSequence.from<Item>(items);
  }
  return rope.append(items);
}
